schema: design-driven

context: |
  Tech stack: TypeScript, React, Nextjs

  # OpenSpec workflow: design-driven
  
  This workflow is centered around having global and local `design.md` files as the single source of truth.
  
  When creating a change's design.md, review only files explicitly indicated by the user and relevant global design documents under specs/[domain]/design.
  
  ## Global design index

  - General creation or refactor for components
    - openspec/specs/components-conventions/design.md

  ## Notes

  When using the `archive` skill, ignore completely the sync skill, do no use it under any circumstance.
